force-app/main/default/objects/GithubUser__c/GithubUser__c.object-meta.xml
<CustomObject>
    <label>GithubUser</label>
    <nameField>
        <label>Login</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GithubUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GithubUser__c/fields/public_gists__c.field-meta.xml
<CustomField>
    <fullName>public_gists__c</fullName>
    <label>public_gists</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GithubUser__c/fields/public_repos__c.field-meta.xml
<CustomField>
    <fullName>public_repos__c</fullName>
    <label>public_repos</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GithubUser__c/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <label>url</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GithubUsers.cls
public with sharing class GithubUsers {
  public static List<Id> createRecords(List<JSONParser.UserProfile> userProfiles){ 
    List<GithubUser__c> githhubUsersToInsert = new List<GithubUser__c>();
    for(JSONParser.UserProfile userProfile : userProfiles){
      githhubUsersToInsert.add(createGithubUser(userProfile));
    }
    insert githhubUsersToInsert;

    List<Id> ids = new List<Id>();
    for(GithubUser__c u : githhubUsersToInsert){
      ids.add(u.Id);
    }
    return ids;
  }

  private static GithubUser__c createGithubUser(JSONParser.UserProfile userProfile){
    return new GithubUser__c(Name = userProfile.login,
                            url__c = userProfile.url,
                            public_repos__c = userProfile.public_repos,
                            public_gists__c = userProfile.public_gists);
  }
}